---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: any
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
                optional: true
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
