---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer
  namespace: default
data:
  ${ADMIN_USER}/networks/ip: "::/0"
  ${ADMIN_USER}/profile: default
  ${ADMIN_USER}/password: ""

  ${READONLY_USER}/networks/ip: "::/0"
  ${READONLY_USER}/profile: readonly
  ${READONLY_USER}/password: ""

  ${GUEST_USER}/networks/ip: "::/0"
  ${GUEST_USER}/profile: guest
  ${GUEST_USER}/password: ""
